### PR TITLE
feat: split config; set default configuration for adapter

### LINKED ISSUE #170: `enablePolkadotSnap` Returns an Error When Using the Default `networkName`
Despite selecting "Westend" as the default network in `snap/src/configuration/predefined.ts`, if the adapter executes its only exposed function, `enablePolkadotSnap()`, without specifying `config.networkName`, then an error will be returned. `enablePolkadotSnap()` should use the default Westend configuration [if the supplied configuration does not specify a network name](https://github.com/ChainSafe/metamask-snap-polkadot/blob/61787c6/packages/adapter/src/index.ts#L27).

### PR DESCRIPTION
**Pull request by Lykhoyda**
Closes #170

### CODE REVIEW

**Comment by mpetrunic** [comment]
What's the reason for moving config to a separate package?

**Comment by Lykhoyda** [comment]
> What's the reason for moving config to a separate package?

We are sharing the config between the adapter and the snap package now. Potentially we could have a more common configuration, so I decided to move it to a separate package

**Comment by mpetrunic** [comment]
> > What's the reason for moving config to a separate package?
> 
> We are sharing the config between the adapter and the snap package now. Potentially we could have a more common configuration in the future, so I decided to move it to a separate package

Woudln't the simpler solution be to just pass network name "westened" instead of entire config or throwing error?

**Comment by Lykhoyda** [comment]
@mpetrunic and I wasn't aware of the discussion about the default network. So we can completely ignore this PR if it's a case

**Comment by danforbes** [comment]
> > > What's the reason for moving config to a separate package?
> > 
> > 
> > We are sharing the config between the adapter and the snap package now. Potentially we could have a more common configuration in the future, so I decided to move it to a separate package
> 
> Woudln't the simpler solution be to just pass network name "westened" instead of entire config or throwing error?

Yes let's not just blindly do exactly what the suggestion is...let's choose a solution that truly speaks to the problem. We want to make it impossible/very, very difficult for the user to do a wrong/confusing thing. It seems like forcing them to select from a set of well-known configs is the way to go, but I'm not sure if that would be good enough for developers that are using the adapter in a pure-JS context, for instance.

**Comment by danforbes** [comment]
@BeroBurny can you please help me get this across the finish line?

**Comment by BeroBurny** [comment]
Good approach but for the current situation is a bit overkill, so closing in favor of #174

**Pull request closed without merging**
